services:
  web:
    build: .
    container_name: flask_app
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - DATABASE_URI=mysql+pymysql://root:anybridges04@db/actividad

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: anybridges04
      MYSQL_DATABASE: actividad
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./persona.sql:/docker-entrypoint-initdb.d/persona.sql

volumes:
  mysql_data:
#hola